application: # AppEngine identifier goes here
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /css
  static_dir: static/css

- url: /fonts
  static_dir: static/fonts

- url: /img
  static_dir: static/img

- url: /js
  static_dir: static/js

- url: .*
  script: main.app